Repository redBorder/cookbook-logstash, pull requests merged in 2024-06, with the labels that each got.

#32 fix curl
  resources/metadata.rb
  resources/providers/config.rb
Labels: kind/bug, size/XS

#43 Improvement/fix lint
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, lint, refactor

#44 Release 2.0.5
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: kind/documentation
