Repository redBorder/cookbook-logstash, pull requests merged in 2024-07, with the labels that each got.

#45 Feature/#17820 add intrusion pipeline
  resources/providers/config.rb
  resources/templates/default/intrusion_darklist.conf.erb
  resources/templates/default/intrusion_encode.conf.erb
  resources/templates/default/intrusion_geoenrich.conf.erb
  resources/templates/default/intrusion_intrusion.conf.erb
  resources/templates/default/intrusion_macvendor.conf.erb
  resources/templates/default/pipelines.yml.erb
Labels: kind/feature, size/L

#46 Release 2.1.0
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/templates/default/intrusion_darklist.conf.erb
  resources/templates/default/intrusion_encode.conf.erb
  resources/templates/default/intrusion_geoenrich.conf.erb
  resources/templates/default/intrusion_intrusion.conf.erb
  resources/templates/default/intrusion_macvendor.conf.erb
  resources/templates/default/pipelines.yml.erb
Labels: kind/feature, size/L

#47 add observation id for sflow
  resources/templates/default/sflow_enrichment.conf.erb
  resources/templates/default/sflow_normalization.conf.erb
Labels: size/M

#49 Release 2.2.0
  CHANGELOG.md
  resources/metadata.rb
  resources/templates/default/sflow_enrichment.conf.erb
  resources/templates/default/sflow_normalization.conf.erb
Labels: size/M, kind/documentation

#48 Feature/incident response
  resources/providers/config.rb
  resources/templates/default/intrusion_incident_enrichment.conf.erb
Labels: kind/feature, size/S
